how-summary: true
show-tags: true
show-fundamentals: true
show-separator: true
show-holdings: true
interval: 5
currency: GBP
currency-summary-only: false
sort: alpha
watchlist:
  - TSLA
  - NET
  - AKAM
  - AAPL
  - ARKW
  - ARKK
  - ARKQ
  - MSFT
  - IGG.L
  - ROO.L
  - GBP=X
  - BTC-GBP
groups:
  - name: Currency
    watchlist:
      - GBP=X
  - name: Crypto
    watchlist: 
      - BTC-USD
